added one line note about status
w3c/ttml3 pull request #40
Opened 2022-02-14 00:12 UTC by himorin

added at the top instead of at some middle point, for ease to be noticed when someone visited to the page.

2022-02-14 00:17 UTC, himorin commented
(please ignore about the build failure. it's just I'm using my fork, and would not be an issue on merging PR - even if failed, this PR does not touch any spec file)

2022-02-14 12:13 UTC, nigelmegitt requested changes
I think we can be even more helpful, suggestion provided.

2022-02-14 12:13 UTC, nigelmegitt commented on README.md
> +specification is currently suspended.
```suggestion
**IMPORTANT: Development of Timed Text Markup Language 3 (TTML3) is currently suspended.**

To raise issues against TTML2 please visit [w3c/ttml2 issues](https://github.com/w3c/ttml2/issues).

This repository serves to hold issues against TTML whose resolution requires a substantive change that is deemed too significant to make in previous versions of TTML.
```

2022-02-15 10:06 UTC, nigelmegitt approved these changes
LGTM

2022-02-15 11:47 UTC, merged